Repository mmasias/PRG1-22-23-ExamenParcial, pull requests merged in 2022-11, with the labels that each got.

#5 Entrega de parcial 1 alumno Diego Moys
  entregas/moysDiego/parcialDiegoMoys.class
  entregas/moysDiego/parcialDiegoMoys.java
Labels: Bien enviado

#4 Entrega Jose Manuel Rasilla
  entregas/rasillaJose/RasillaJoseManuel.java
  entregas/rasillaJose/readme.md
Labels: Bien enviado

#6 Examen Parcial Brenda Lopes
  entregas/lopesBrenda/1.md
  entregas/lopesBrenda/ExamenParcial.java
Labels: Bien enviado

#7 Entrega Parcial 1 (Carrera de camellos) Javier Salmerón
  entregas/salmeronJavier/carreraCamellos.java
Labels: Bien enviado

#8 Examen Parcial. Daniel Puente
  entregas/puenteDaniel/ExamenParcial.java
  entregas/puenteDaniel/Readme.md
Labels: Bien enviado

#11 examen morenoSergio
  entregas/morenoSergio/sergioMoreno.java
Labels: Bien enviado

#13 Examen Parcial, Manuela Grizoni
  entregas/manuelaGrizoni/examenParcial.java
Labels: Bien enviado

#16 Examen Programación - Andrés Alarcón
  entregas/andrésAlarcón/CarreraCaballos/.vscode/settings.json
  entregas/andrésAlarcón/CarreraCaballos/src/CarreraCamellos.java
Labels: Bien enviado

#17 Entrega examen parcial
  entregas/BayasAnibal/BayasAnibal.java
  entregas/BayasAnibal/readme.md
Labels: Bien enviado

#19 Carrera
  entregas/barriosOmar/Carrera.java
Labels: Bien enviado

#21 Parcial Sara Patiño
  entregas/patinoSara/README.md
  entregas/patinoSara/carreraCamellos.java
Labels: Bien enviado

#22 Create carreraCamellos.java
  entregas/celayaIker/carreraCamellos.java
Labels: Bien enviado

#25 Examen Javier Cader
  entregas/javierCader/carreraCamellos/.vscode/settings.json
  entregas/javierCader/carreraCamellos/README.md
  entregas/javierCader/carreraCamellos/bash.exe.stackdump
  entregas/javierCader/carreraCamellos/src/App.java
Labels: Bien enviado

#26 Create examenFinal.java
  entregas/valentinaArias/examenFinal.java
Labels: Bien enviado

#27 Parcial1.md
  entregas/lydiaGarcía/Parcial1.md
Labels: Bien enviado

#28 Examen programación Camellos
  entregas/mayenSergio/carreraCamellos.java
Labels: Bien enviado

#29 EXAMEN PARCIAL
  entregas/delrioMario/ExamenCarreraCamellos.java
  entregas/delrioMario/Readme.md
Labels: Bien enviado

#30 Entrega Examen Parcial
  entregas/alvaroLostal/ExamenParcialBase.java
  entregas/alvaroLostal/ExamenParcialExtendido.java
  entregas/alvaroLostal/readme.md
Labels: Bien enviado

#32 examen Raul Pelayo
  entregas/raulPelayo/examen.java
  entregas/raulPelayo/readme.md
Labels: Bien enviado

#34 Entrega reto camello examen parcial Diego García Niño
  entregas/garcíaDiego/README.md
  entregas/garcíaDiego/RetoCamello.java
Labels: Bien enviado

#35 Examen Carrera de camellos Pablo Arce
  entregas/arcePablo/CarreraDeCamellos.class
  entregas/arcePablo/CarreraDeCamellos.java
Labels: Bien enviado

#39 Diego Barraza Examenparcial
  entregas/barrazadiego/Examenparcial.java
Labels: Bien enviado

#42 examen davidGarcia
  entregas/garciaDavid/CarreraDeCamellosdavid.java
  entregas/garciaDavid/readme.md
Labels: Bien enviado

#43 ExamenParcial
  entregas/aurelioOchoa/ochoaAurelio.java
Labels: Fuera de tiempo

#44 examen
  entregas/mauraMartinez.md/Examen parcial
  entregas/mauraMartinez/examenParcial.java
  entregas/mauraMartinez/examenParcial.md
Labels: Fuera de tiempo

#45 Parcial1 - JoseSalceda
  entregas/Parcial1 - JoseSalceda
  entregas/joseSalceda/Parcial
Labels: Fuera de tiempo, Mal enviado

#46 Entrega Examen
  entregas/leonEdgar/examen.java
Labels: Fuera de tiempo

#47 Examen Parcial Carrera de Camellos (Miguel Gómez)
  entregas/Gomezmiguel/CarreraCamellos.java
  entregas/Gomezmiguel/Read.md
Labels: Fuera de tiempo

#48 adrianGarcia
  entregas/adrianGarcia/Camellos2.java
  entregas/adrianGarcia/readme.md
Labels: Fuera de tiempo
